name: Publish 'latest' Docker Image

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fau-cdi/hangover:latest
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
      - uses: docker/build-push-action@v3
        with:
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          platforms: ${{ env.PLATFORMS }}
          pull: true
          push: true