name: CI

on: [push, pull_request]

env:
  GO_VERSION: '~1.20'
  GO_STABLE: 'true'
  NODE_VERSION: '16'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: ${{ env.GO_STABLE }}
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run 'make deps'
        run: make deps
      - name: Run 'make generate'
        run: make generate
      - name: Run 'make test'
        run: make test
      - name: Run 'make all'
        run: make all
      - uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: dist
      - name: Upload Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/hangover_darwin
            dist/hangover_linux_amd64
            dist/hangover_windows_amd64.exe
            dist/n2j_darwin
            dist/n2j_linux_amd64
            dist/n2j_windows_amd64.exe
